project_id = "zkvurokcdlkuygrsfjqr"

[auth.email]
enable_signup = true
enable_confirmations = true
sender_name = "Even Playground"
sender_email = "noreply@evenplayground.com"

[auth.email.template.confirmation]
subject = "Confirm your Even Playground account"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.magic_link]
subject = "Your Even Playground login link"
content_path = "./supabase/templates/magic_link.html"

[auth.email.template.recovery]
subject = "Reset your Even Playground password"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.invite]
subject = "You've been invited to Even Playground"
content_path = "./supabase/templates/invite.html"

[auth.email.template.email_change]
subject = "Confirm your email change"
content_path = "./supabase/templates/email_change.html"